[target.aarch64-apple-darwin]
image="freeznet/aarch64-apple-darwin-cross:11.3"

[target.aarch64-unknown-linux-gnu]
image = "japaric/aarch64-unknown-linux-gnu"

[target.x86_64-apple-darwin]
image="freeznet/x86_64-apple-darwin-cross:11.3"
